name: Upload Asset
description: Upload asset to release
inputs:
  upload_url:
    description: url where to upload assets
    required: true
  asset_path:
    description: path to asset
    required: true
  asset_name:
    description: displayed asset name
    required: true
  label:
    description: label
    required: false
    default: ""
  content_type:
    description: content-type
    required: true
runs:
  using: "composite"
  steps:
    - name: Upload Assets
      shell: bash
      run: |
        curl -H "Authorization: token ${{ github.TOKEN }}" \
          -H "Content-Type: ${{ inputs.content_type }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -F file=@${{ inputs.asset_path }} \
          ${{ inputs.upload_url }}?name=${{ inputs.asset_name }}&label=${{ inputs.label }}
