name: Create Release
description: Create release from specific tag
inputs:
  tag:
    description: Tag to release
    required: true
  body:
    description: Body of release
    required: false
    default: ""

outputs:
  upload_url:
    value: ${{ steps.create_release.outputs.upload_url }}
    description: URL where to upload assets

runs:
  using: "composite"
  steps:
    - name: Create Release
      id: create_release
      shell: bash
      run: |
        body=$(cat ${{ inputs.body }})
        echo $body
        url=$(gh api --method POST \
          -H "Accept: application/vnd.github.v3+json" \
          /repos/${{ github.repository }}/releases \
          -f tag_name='${{ inputs.tag }}' \
          -f body="$body" \
        | jq --raw-output .upload_url \
        | sed -r "s/\{.*\}//g" )
        echo $url
        echo "::set-output name=upload_url::$(echo $url)"