name: Firebase App

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
  workflow_dispatch:

jobs:
  firebase:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - run: |
          curl -sL firebase.tools | bash
          echo ${{ secrets.FIREBASE_CREDENTIALS }} | base64 -d > key.json
          export GOOGLE_APPLICATION_CREDENTIALS=key.json
          firebase apps:android:sha:list ${{ secrets.FIREBASE_APP_ID }}