name: Create release on push tag
on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Create dummy secrets
        run: echo "BASE_URL=localhost" > local.properties

#      - uses: gradle/gradle-build-action@v2
#
#      - name: Build
#        run: ./gradlew build

      - name: Get commit summary
        id: get_commit_summary
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          PREVIOUS_TAG= #$(git tag --sort=-creatordate | sed -n 2p)
          COMMIT_SUMMARY="$(git log --oneline --pretty=tformat:"%h %s")"
          COMMIT_SUMMARY="${COMMIT_SUMMARY//$'\n'/'\\n'}"
          echo ::set-output name=COMMIT_SUMMARY::$COMMIT_SUMMARY

      - name: Create Release
        id: create_release
        uses: ./.github/actions/create_release
        with:
          tag: ${{ github.ref_name }}
          body: |
            ${{ steps.get_commit_summary.outputs.COMMIT_SUMMARY }}

      - name: Upload debug.apk
        uses: ./.github/actions/upload_asset
        env:
          URL: ${{ steps.create_release.outputs.upload_url }}
        with:
          upload_url: ${{ env.URL }}
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: debug.apk
          label: debug
          content_type: application/zip

      - name: Upload release-unsigned.apk
        uses: ./.github/actions/upload_asset
        env:
          URL: ${{ steps.create_release.outputs.upload_url }}
        with:
          upload_url: ${{ env.URL }}
          asset_path: app/build/outputs/apk/release/app-release-unsigned.apk
          asset_name: release-unsigned.apk
          label: release
          content_type: application/zip
