name: Create release on push tag
on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Create dummy secrets
        run: echo "BASE_URL=localhost" > local.properties

      - uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew build
#        run: |
#          mkdir -p app/build/outputs/apk/{debug,release}
#          echo "debug" > app/build/outputs/apk/debug/app-debug.apk
#          echo "release" > app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Get commit summary
        id: get_commit_summary
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo $TAG
          PREVIOUS_TAG= #$(git tag --sort=-creatordate | sed -n 2p)
          git log --oneline --pretty=tformat:"%h %s" > commit_summary
          echo ::set-output name=TAG::$TAG
          echo ::set-output name=COMMIT_SUMMARY::$(realpath commit_summary)

      - name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.get_commit_summary.outputs.TAG }} \
            --generate-notes \
            app/build/outputs/apk/debug/app-debug.apk \
            app/build/outputs/apk/release/app-release-unsigned.apk
